name: Scala CI

on:
  push:
    branches: '*'

# Correct: Comma added
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Scala
        uses: actions/setup-scala@v3
        with:
          scala-version: '3.3.1'
      - name: Build the Project
        run: sbt build