name: Scala CI

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Project
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: [my-scala-build]
          file: ./Dockerfile