name: Scala CI

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Scala Environment
        uses: actions/setup-docker@v3
        with:
          docker-version: 'latest'

      - name: Build the Project
        run: |
          docker run --rm -v "${GITHUB_WORKSPACE}:/app" scala:3.3.1 sbt build